name: Unzip and Commit

on:
  push:
    branches:
      - main

jobs:
  unzip_commit_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Unzip Luna-main.zip and clean up
        run: |
          unzip -q "Luna-main.zip" -d temp_unzip/
          mv temp_unzip/Luna-main/* ./
          rm -rf temp_unzip/ Luna-main/

      - name: Commit unzipped files
        run: |
          git config --global user.name "Endtrz"
          git config --global user.email "Endtrz@users.noreply.github.com"
          git add .
          git commit -m "Initial commit"
          git push
